### ISSUE TITLE
failed to decipher auth data

### ISSUE THREAD

**Issue by vorzap** [loganm/sfdx-hydrate#5]
I keep getting this 

> failed to deciper auth data. reason: Unsupported state or unable to authenticate data.

error when trying both available commands.

**Comment by loganm** [comment]
My gut instinct suggests that may be an auth error from core SFDX.

Can you send the result of this command,
and the command that you're running?
```
sfdx force:org:list --verbose
```

I also found some stack exchange threads on that error message that have a few things to try.

**Comment by loganm** [comment]
@vorzap How's it going. Still need a hand?

**Comment by loganm** [comment]
I'm going to close this issue, but if you ever want a hand figuring it out, let me know.
